# -*- coding: utf-8 -*-
"""verify_admin_partner.py — 지역 파트너 콘솔(mock 모드) 화면 점검.  - 클로드
실행: python3 verify_admin_partner.py   (사이트 루트에서; file:// 로 admin/*.html, en/confirm.html 을 연다)
운영자 시점과 파트너 시점(?as=partner)을 각각 열어 카드·버튼·다이얼로그·로컬 재생을 확인한다.
"""
import os, sys, re
from playwright.sync_api import sync_playwright
ROOT = os.path.dirname(os.path.abspath(__file__))
BASE = 'file:///' + ROOT.replace('\\', '/').lstrip('/') + '/admin/'
EN = 'file:///' + ROOT.replace('\\', '/').lstrip('/') + '/en/'
res = []; errs = []
def ok(name, cond, extra=''):
    res.append((name, bool(cond), extra)); print(('PASS ' if cond else 'FAIL ') + name + (' | ' + str(extra) if extra and not cond else ''))
with sync_playwright() as p:
    b = p.chromium.launch()
    def newpage(w=1280, h=900):
        ctx = b.new_context(viewport={'width': w, 'height': h}); pg = ctx.new_page()
        pg.on('console', lambda m: errs.append((pg.url, m.text)) if m.type == 'error' and 'ERR_TUNNEL' not in m.text and 'net::' not in m.text else None)
        pg.on('pageerror', lambda e: errs.append((pg.url, str(e))))
        return ctx, pg
    def login(pg, as_partner=False):
        pg.goto(BASE + 'index.html'); pg.fill('#em', 'ops@matchgo.ai'); pg.fill('#pw', 'x'); pg.click('button[type=submit]'); pg.wait_for_url('**/dashboard.html')
        if as_partner:
            pg.goto(BASE + 'dashboard.html?as=partner'); pg.wait_for_timeout(200)

    # ---------- 운영자 ----------
    ctx, pg = newpage(); login(pg)
    ok('HQ nav has partner-orgs/settlements, no my-org', pg.locator('nav a[href="partner-orgs.html"]').count() >= 1 and pg.locator('nav a[href="settlements.html"]').count() >= 1 and pg.locator('nav a[href="my-org.html"]').count() == 0)
    ok('HQ dashboard intervention widget', pg.locator('#interventions').count() == 1 and pg.locator('#interventions tbody tr').count() >= 1)
    n0 = pg.locator('#interventions tbody tr').count()
    pg.click('#interventions button[data-int]'); pg.wait_for_selector('.dlg textarea, .dlg input', timeout=3000)
    pg.fill('.dlg textarea', '파트너에게 전화로 확인'); pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    ok('HQ intervention resolve (local replay)', pg.locator('#interventions tbody tr').count() == n0 - 1 or pg.locator('#interventions').count() == 0)

    pg.goto(BASE + 'rfps.html'); pg.wait_for_timeout(200)
    ok('rfps deleg/region filters present', pg.locator('#fd').count() == 1 and pg.locator('#fr').count() == 1)
    pg.select_option('#fd', 'delegated'); pg.wait_for_timeout(150)
    deleg = int(re.sub(r'\D', '', pg.text_content('#cnt')) or 0)
    ok('rfps delegated filter narrows', deleg > 0, deleg)
    pg.select_option('#fd', ''); pg.select_option('#fr', 'TH'); pg.wait_for_timeout(150)
    th = int(re.sub(r'\D', '', pg.text_content('#cnt')) or 0)
    ok('rfps region TH filter', th >= deleg, th)
    # 위임 건 상세
    pg.select_option('#fr', ''); pg.select_option('#fd', 'delegated'); pg.wait_for_timeout(150)
    pg.click('.seg button[data-v=list]'); href = pg.get_attribute('table a.rowlink', 'href'); pg.goto(BASE + href); pg.wait_for_timeout(200)
    ok('rfp detail assign card', pg.locator('#h-asg').count() == 1 and '파트너 위임' in pg.text_content('#h-asg ~ dl, section[aria-labelledby=h-asg]'))
    ok('rfp detail HQ buttons', pg.locator('[data-ptr=hold]').count() == 1 and pg.locator('[data-ptr=takeover]').count() == 1)
    pg.click('[data-ptr=takeover]'); pg.wait_for_selector('.dlg', timeout=3000); pg.fill('.dlg #dlgWhy', '오거나이저 VOC · 본사 직접 처리'); pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    ok('rfp takeover → 본사 인계 chip', '본사 인계' in pg.text_content('section[aria-labelledby=h-asg]'))
    ok('rfp takeover shows release', pg.locator('[data-ptr=release]').count() == 1)
    pg.click('[data-ptr=release]'); pg.wait_for_selector('.dlg', timeout=3000); pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    ok('rfp release → 파트너 위임', '파트너 위임' in pg.text_content('section[aria-labelledby=h-asg]'))
    # 대리 입력 상태 셀 (bidding 건)
    pg.goto(BASE + 'rfps.html?deleg=delegated&state=bidding'); pg.wait_for_timeout(200); pg.click('.seg button[data-v=list]')
    hrefs = [pg.get_attribute('table a.rowlink >> nth=' + str(i), 'href') for i in range(pg.locator('table a.rowlink').count())]
    found_proxy = False; found_wait = False
    for h in hrefs:
        pg.goto(BASE + h); pg.wait_for_timeout(150)
        found_proxy = found_proxy or pg.locator('[data-ptr=proxy]').count() >= 1
        found_wait = found_wait or ('호텔 확인 대기' in (pg.text_content('#invTable') or ''))
    ok('proxy cell in invitation table', found_proxy)
    ok('proxy_entered demo row shows 확인 대기', found_wait)
    # 정산
    pg.goto(BASE + 'settlements.html'); pg.wait_for_timeout(200)
    ok('settlements list rows', pg.locator('table tbody tr a.rowlink').count() >= 1)
    href = pg.get_attribute('table tbody tr a.rowlink', 'href'); pg.goto(BASE + href); pg.wait_for_timeout(200)
    ok('settlement detail renders', pg.locator('#h-b').count() == 1 and pg.locator('#h-m').count() == 1)
    if pg.locator('[data-st=approve_commission]').count():
        pg.click('[data-st=approve_commission]'); pg.wait_for_selector('.dlg', timeout=3000); pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
        ok('HQ approve commission → 커미션 확정', '커미션 확정' in pg.text_content('.dh'))
    # 지역 파트너 조직
    pg.goto(BASE + 'partner-orgs.html'); pg.wait_for_timeout(200)
    ok('partner-orgs list', pg.locator('table tbody tr').count() >= 2)
    pg.goto(BASE + 'partner-orgs.html?code=TMTHAI'); pg.wait_for_timeout(200)
    ok('partner-org detail cards', pg.locator('#h-oi').count() == 1 and pg.locator('#h-ou').count() == 1)
    u0 = pg.locator('#h-ou ~ div tbody tr, section[aria-labelledby=h-ou] tbody tr').count()
    pg.click('[data-org=invite]'); pg.wait_for_selector('.dlg', timeout=3000); pg.fill('.dlg #iv-name', '테스트'); pg.fill('.dlg #iv-email', 'test@tmthai.example'); pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    ok('HQ invite adds user row', pg.locator('section[aria-labelledby=h-ou] tbody tr').count() == u0 + 1)
    pg.click('[data-org=region]'); pg.wait_for_selector('.dlg', timeout=3000); pg.select_option('.dlg #rg-code', 'VN-DAD'); pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    ok('HQ region set adds VN-DAD', 'VN-DAD' in pg.text_content('section[aria-labelledby=h-oi]'))
    # 호텔 상세 (HQ) — 지역 카드
    pg.goto(BASE + 'partners.html'); pg.wait_for_timeout(200); pg.click('.segs button[data-s=approved]'); href = pg.get_attribute('table a.hn', 'href'); pg.goto(BASE + href); pg.wait_for_timeout(200)
    ok('hotel detail region card', pg.locator('#h-rg').count() == 1 and pg.locator('[data-ptr=hotel-region]').count() == 1)
    ok('hotel detail commission card', pg.locator('#cmSection').count() == 1 and pg.locator('#cmSection [data-ptr=cm-set]').count() == 1)
    # ---- 호텔 커미션: 목록 배지 · 상세 카드 · 요율 제안 · 재발송
    pg.goto(BASE + 'partners.html'); pg.wait_for_timeout(200); pg.click('.segs button[data-s=approved]')
    ok('list badge 요율 합의 필요 (p11 only)', pg.locator('.ptable tbody tr[data-id=p11]').inner_text().count('요율 합의 필요') == 1 and pg.locator('.ptable tbody tr[data-id=p1]').inner_text().count('요율 합의 필요') == 0)
    ok('list badge 동의 대기 (p14)', '동의 대기' in pg.locator('.ptable tbody tr[data-id=p14]').inner_text())
    # rfp 초대 카드: 합의 전 호텔 disabled + 배지, 초대 불가
    pg.goto(BASE + 'rfps.html'); pg.wait_for_timeout(150)
    pg.evaluate("(function(){var r=MICEGO.get('MG-2610-017');r.destination='발리';r.regionCode='ID-DPS';MICEGO.save();})()")
    pg.goto(BASE + 'rfp.html?id=MG-2610-017'); pg.wait_for_timeout(250)
    ok('invite: unagreed p11 checkbox disabled + badge', pg.locator('#plist input[data-p=p11]').is_disabled() and '요율 합의 필요' in pg.locator('#plist li:has(input[data-p=p11])').inner_text())
    ok('invite: agreed p12 checkbox enabled', pg.locator('#plist input[data-p=p12]').is_enabled())
    pg.evaluate("MICEGO.invite(MICEGO.get('MG-2610-017'),['p11'])"); pg.wait_for_timeout(100)
    t = pg.inner_text('#toasts'); ok('invite p11 alone refused (COMMISSION_NOT_AGREED)', '동의한 호텔이 없어' in t, t)
    ok('no invitation created for p11', pg.evaluate("MICEGO.get('MG-2610-017').invitations.filter(function(i){return i.hotelId==='p11'}).length") == 0)
    pg.goto(BASE + 'partner.html?id=p11'); pg.wait_for_timeout(200)
    ok('p11 header badge 요율 합의 필요', '요율 합의 필요' in pg.inner_text('.dh'))
    ok('p11 card: 합의 전, 기준 문구, 재발송 없음', '합의 전' in pg.inner_text('#cmRateNow') and '순액' in pg.inner_text('#cmSection') and '세금·봉사료 제외' in pg.inner_text('#cmSection') and pg.locator('[data-ptr=cm-resend]').count() == 0)
    pg.click('[data-ptr=cm-set]'); pg.wait_for_selector('.dlg #cmRate', timeout=3000)
    ok('HQ dialog: range hint + reason field', '5~20%' in pg.inner_text('#cmHint') and pg.locator('#cmReason').count() == 1)
    pg.fill('#cmRate', '25'); pg.click('.dlg [data-x=ok]'); ok('HQ out of range needs reason', '사유' in pg.inner_text('.dlg-err'), pg.inner_text('.dlg-err'))
    pg.fill('#cmReason', '프리미엄 단독 계약 조건'); pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(150)
    ok('p11 proposal saved: 동의 대기 + 25% + 본사 예외', '동의 대기' in pg.inner_text('.dh') and '25%' in pg.inner_text('#cmSection') and '본사 예외' in pg.inner_text('#cmHist'), pg.inner_text('#cmSection')[:200])
    ok('p11 resend button appears after proposal', pg.locator('[data-ptr=cm-resend]').count() == 1)
    pg.goto(BASE + 'partner.html?id=p14'); pg.wait_for_timeout(200)
    ok('p14 pending 12% shown, agreed stays 10%', '10%' in pg.inner_text('#cmRateNow') and '12%' in pg.inner_text('#cmSection') and '발송 1회' in pg.inner_text('#cmSection'))
    pg.click('[data-ptr=cm-resend]'); pg.wait_for_selector('.dlg', timeout=3000); pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(150)
    ok('p14 resend → 발송 2회 + history', '발송 2회' in pg.inner_text('#cmSection') and '링크 다시 보냄' in pg.inner_text('#cmHist'), pg.inner_text('#cmSection')[:300])
    # 제안 후에도 합의 전이므로 초대 불가 (배지는 동의 대기)
    pg.goto(BASE + 'rfp.html?id=MG-2610-017'); pg.wait_for_timeout(250)
    ok('invite: p11 stays disabled after proposal (동의 대기)', pg.locator('#plist input[data-p=p11]').is_disabled() and '동의 대기' in pg.locator('#plist li:has(input[data-p=p11])').inner_text())
    # 정산 상세: 합의 요율(읽기 전용) 행
    pg.goto(BASE + 'settlement.html?ref=ST-2610-K7QD'); pg.wait_for_timeout(200)
    ok('settlement shows 합의 요율 10% + 순액 label', '10%' in pg.inner_text('#agreedRate') and '순액: 세금·봉사료 제외' in pg.inner_text('#h-m ~ dl'), pg.inner_text('#agreedRate'))
    ok('settlement 합의 요율 is not editable', pg.locator('#agreedRate input').count() == 0)
    ctx.close()

    # ---------- 파트너 (TMTHAI 관리자) ----------
    ctx, pg = newpage(); login(pg, True)
    ok('partner side-sub label', '파트너 콘솔' in pg.text_content('.side-sub'))
    ok('partner nav: my-org yes, members/settings/partner-orgs no', pg.locator('nav a[href="my-org.html"]').count() >= 1 and pg.locator('nav a[href="members.html"]').count() == 0 and pg.locator('nav a[href="settings.html"]').count() == 0 and pg.locator('nav a[href="partner-orgs.html"]').count() == 0)
    ok('partner dashboard summary', '담당 지역' in pg.text_content('main'))
    pg.goto(BASE + 'rfps.html'); pg.wait_for_timeout(200)
    ok('partner rfps: no deleg filter', pg.locator('#fd').count() == 0)
    pg.click('.seg button[data-v=list]'); n = pg.locator('table a.rowlink').count()
    ok('partner sees only own delegated rfps', n > 0 and n < 12, n)
    pg.goto(BASE + pg.get_attribute('table a.rowlink', 'href')); pg.wait_for_timeout(200)
    ok('partner: no copyTrack, no owner card', pg.locator('#copyTrack').count() == 0 and pg.locator('#h-own').count() == 0)
    ok('partner: masked organizer card with reveal', pg.locator('[data-ptr=reveal]').count() == 1)
    pg.click('[data-ptr=reveal]'); pg.wait_for_timeout(300)
    if pg.locator('.dlg').count(): pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    ok('partner: reveal shows identity + 열람 기록', '열람 기록됨' in pg.text_content('section[aria-labelledby=h-org]'))
    ok('partner: no HQ takeover buttons', pg.locator('[data-ptr=takeover]').count() == 0)
    # 호텔 등록
    pg.goto(BASE + 'partners.html'); pg.wait_for_timeout(200)
    ok('partner hotels: register button + region scope', pg.locator('#regHotel').count() == 1)
    pg.click('#regHotel'); pg.wait_for_selector('.dlg', timeout=3000)
    pg.fill('.dlg #h-name', 'Test Resort Pattaya'); pg.fill('.dlg #h-loc', 'Pattaya'); pg.fill('.dlg #h-cap', '300'); pg.fill('.dlg #h-cn', 'Somchai'); pg.fill('.dlg #h-ce', 'sales@testresort.com'); pg.fill('.dlg #h-dom', 'testresort.com')
    pg.click('.dlg .btn.primary'); pg.wait_for_timeout(300)
    pg.click('.segs button[data-s=queue]'); pg.wait_for_timeout(100)
    ok('partner hotel registered in queue', 'Test Resort Pattaya' in pg.text_content('#res'))
    # 내 조직
    pg.goto(BASE + 'my-org.html'); pg.wait_for_timeout(200)
    ok('my-org renders org + users', pg.locator('#h-oi').count() == 1 and pg.locator('#h-ou').count() == 1)
    ok('my-org: partner admin cannot edit org info', pg.locator('[data-org=edit]').count() == 0 and pg.locator('[data-org=invite]').count() == 1)
    # 정산 (파트너)
    pg.goto(BASE + 'settlements.html'); pg.wait_for_timeout(200)
    ok('partner settlements only own', pg.locator('table tbody tr a.rowlink').count() >= 1 and pg.locator('#fp').count() == 0)
    # ---- 호텔 커미션: 파트너 관리자는 범위(5~20%) 안에서만
    pg.goto(BASE + 'partner.html?id=p7'); pg.wait_for_timeout(200)
    ok('partner sees commission card, 10% agreed', '10%' in pg.inner_text('#cmRateNow') and pg.locator('[data-ptr=cm-set]').count() == 1)
    pg.click('[data-ptr=cm-set]'); pg.wait_for_selector('.dlg #cmRate', timeout=3000)
    ok('partner dialog: no reason field, range hint', pg.locator('#cmReason').count() == 0 and '5~20%' in pg.inner_text('#cmHint'))
    pg.fill('#cmRate', '25'); pg.click('.dlg [data-x=ok]'); ok('partner blocked above range', '5~20%' in pg.inner_text('.dlg-err') and pg.locator('.dlg').count() == 1, pg.inner_text('.dlg-err'))
    pg.fill('#cmRate', '3'); pg.click('.dlg [data-x=ok]'); ok('partner blocked below range', pg.locator('.dlg').count() == 1)
    pg.fill('#cmRate', '12.5'); pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(150)
    ok('partner proposal 12.5% saved (동의 대기)', '12.5%' in pg.inner_text('#cmSection') and '동의 대기' in pg.inner_text('.dh') and '파트너 관리자' in pg.inner_text('#cmHist'), pg.inner_text('#cmSection')[:200])
    pg.evaluate("MICEGO.me.role='partner_member'; MICEGO.onChange()"); pg.wait_for_timeout(100)
    ok('partner_member: read-only commission card', pg.locator('#cmSection').count() == 1 and pg.locator('[data-ptr=cm-set]').count() == 0 and pg.locator('[data-ptr=cm-resend]').count() == 0)
    pg.evaluate("MICEGO.me.role='partner_admin'; MICEGO.onChange()")
    # ---- 정산 입력: 합의 요율 readonly + 체크 시 잠금 해제·사유 필수
    pg.evaluate("(function(){var s=MICEGO.data().settlements[0];s.status='pending_commission';s.contractAmount=null;s.commissionAmount=null;s.commissionRatePct=null;MICEGO.save();})()")
    pg.goto(BASE + 'settlement.html?ref=ST-2610-K7QD'); pg.wait_for_timeout(200)
    pg.click('[data-st=submit_commission]'); pg.wait_for_selector('.dlg #st-rate', timeout=3000)
    ok('settlement dialog: rate prefilled 10 readonly, basis locked', pg.input_value('#st-rate') == '10' and pg.get_attribute('#st-rate', 'readonly') is not None and pg.is_disabled('#st-basis') and '순액: 세금·봉사료 제외' in pg.inner_text('.dlg'))
    pg.fill('#st-contract', '40000'); pg.check('#st-dev')
    ok('deviation checkbox unlocks rate', pg.get_attribute('#st-rate', 'readonly') is None and pg.is_enabled('#st-basis'))
    pg.fill('#st-rate', '12'); pg.click('.dlg [data-x=ok]'); ok('deviation requires note', '사유' in pg.inner_text('.dlg-err') and pg.locator('.dlg').count() == 1, pg.inner_text('.dlg-err'))
    pg.uncheck('#st-dev'); ok('unchecking restores agreed rate + lock', pg.input_value('#st-rate') == '10' and pg.get_attribute('#st-rate', 'readonly') is not None)
    pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(200)
    ok('agreed-rate submit → 승인 대기 without deviation flag', '커미션 승인 대기' in pg.inner_text('.dh') and '합의 요율과 다름' not in pg.inner_text('.dh') and '10%' in pg.inner_text('#h-m ~ dl'), pg.inner_text('.dh'))
    pg.evaluate("(function(){var s=MICEGO.data().settlements[0];s.status='pending_commission';MICEGO.save();})()")
    pg.goto(BASE + 'settlement.html?ref=ST-2610-K7QD'); pg.wait_for_timeout(200)
    pg.click('[data-st=submit_commission]'); pg.wait_for_selector('.dlg #st-rate', timeout=3000)
    pg.fill('#st-contract', '40000'); pg.check('#st-dev'); pg.fill('#st-rate', '12'); pg.fill('#st-note', '호텔과 이벤트 패키지 별도 합의')
    pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(200)
    ok('deviation with note → flag 합의 요율과 다름', '합의 요율과 다름' in pg.inner_text('.dh') and '12%' in pg.inner_text('#h-m ~ dl') and '10%' in pg.inner_text('#agreedRate'), pg.inner_text('.dh'))
    ctx.close()

    # ---------- accept.html / en/confirm.html (demo) ----------
    ctx, pg = newpage(); pg.goto(BASE + 'accept.html'); pg.wait_for_timeout(500)
    ok('accept page ready in demo', pg.locator('#afSubmit').is_enabled())
    pg.fill('#pw', 'abcdef1234'); pg.fill('#pw2', 'abcdef1234'); pg.check('#agree'); pg.click('#afSubmit'); pg.wait_for_url('**/dashboard.html?as=partner', timeout=5000)
    ok('accept demo → partner dashboard', True)
    pg.goto(EN + 'confirm.html?t=abcdefghijklmnop1234'); pg.wait_for_timeout(300)
    ok('confirm page review state', pg.get_attribute('html', 'data-state') == 'review')
    pg.click('#dpBtn'); ok('confirm dispute box opens', not pg.locator('#dpBox').is_hidden())
    pg.click('#cfBtn'); pg.wait_for_timeout(100)
    ok('confirm demo → done', pg.get_attribute('html', 'data-state') == 'done')
    pg.goto(EN + 'confirm.html?t=short'); pg.wait_for_timeout(200)
    ok('confirm invalid token', pg.get_attribute('html', 'data-state') == 'invalid')
    pg.goto(EN + 'commission.html?t=abcdefghijklmnop1234'); pg.wait_for_timeout(300)
    ok('commission page review state', pg.get_attribute('html', 'data-state') == 'review')
    ok('commission accept disabled until checked', pg.is_disabled('#cmBtn'))
    pg.check('#cmAgree'); ok('commission accept enabled after check', pg.is_enabled('#cmBtn'))
    pg.click('#cmBtn'); pg.wait_for_timeout(100)
    ok('commission demo → done', pg.get_attribute('html', 'data-state') == 'done')
    pg.goto(EN + 'commission.html?t=short'); pg.wait_for_timeout(200)
    ok('commission invalid token', pg.get_attribute('html', 'data-state') == 'invalid')
    pg.goto(EN + 'commission.html?t=abcdefghijklmnop1234&state=expired'); pg.wait_for_timeout(200)
    ok('commission expired preview', pg.get_attribute('html', 'data-state') == 'expired')
    ctx.close()
    b.close()

bad = [e for e in errs if 'favicon' not in e[1] and 'fonts.g' not in e[1] and 'cdn.jsdelivr' not in e[1]]
ok('no console/page errors', not bad, bad[:5])
fails = [r for r in res if not r[1]]
print('\nTOTAL', len(res), 'FAIL', len(fails))
sys.exit(1 if fails else 0)
