from playwright.sync_api import sync_playwright
import re
import os
SITE=os.environ.get('MG_SITE_DIR') or os.path.dirname(os.path.abspath(__file__))
SHOTS=os.path.join(SITE,'admin_shots'); os.makedirs(SHOTS,exist_ok=True)
BASE='file://'+SITE+'/admin/'
res=[];errs=[]
def ok(n,c,e=''):
    res.append((n,bool(c))); print(('PASS ' if c else 'FAIL ')+n+((' | '+str(e)) if not c else ''))
with sync_playwright() as p:
    b=p.chromium.launch()
    def newpage(w=1280,h=900):
        ctx=b.new_context(viewport={'width':w,'height':h}); pg=ctx.new_page()
        pg.on('console',lambda m: errs.append((pg.url,m.text)) if m.type=='error' and 'ERR_' not in m.text else None)
        pg.on('pageerror',lambda e: errs.append((pg.url,str(e))))
        return ctx,pg
    def login(pg):
        pg.goto(BASE+'index.html'); pg.fill('#em','ops@matchgo.ai'); pg.fill('#pw','x'); pg.click('button[type=submit]'); pg.wait_for_url('**/dashboard.html')
    def toast(pg): return pg.inner_text('#toasts')
    def ids(pg): return pg.eval_on_selector_all('.mtable tbody tr[data-id]','e=>e.map(x=>x.dataset.id)')
    def acts(pg): return sorted(pg.eval_on_selector_all('#tbtns [data-act]','e=>e.map(x=>x.dataset.act)'))
    def dlg_ok(pg,reason=None,note=None):
        if reason: pg.select_option('#dlgReason',reason)
        if note: pg.fill('#dlgNote',note)
        pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(120)
    def state(pg): return pg.evaluate("JSON.parse(sessionStorage.getItem('micego_admin_state_v1'))")
    ctx,pg=newpage(); login(pg)
    # nav + dashboard
    nav=pg.eval_on_selector_all('.side nav a','e=>e.map(x=>x.getAttribute("href"))'); ok('nav order partners,members,feedback,settings',[h for h in nav if h in ('partners.html','members.html','feedback.html','settings.html')]==['partners.html','members.html','feedback.html','settings.html'] and nav[-1]=='settings.html',nav)  # 2026-09-28: 파트너 콘솔이 settlements·partner-orgs 메뉴를 사이에 추가 → 상대 순서만 검사
    ok('members badge 1',pg.inner_text('.side a[href="members.html"] .nav-badge')=='1')
    ok('dashboard acc card','연결 요청 대기 1건' in pg.inner_text('#accSum') and '잠긴 계정 1건' in pg.inner_text('#accSum'),pg.inner_text('#accSum'))
    pg.click('#accSum [data-key=linkreq]'); pg.wait_for_url('**/members.html?filter=link'); ok('dash link -> filter',ids(pg)==['m1'],ids(pg))
    pg.goto(BASE+'members.html?state=locked'); ok('dash locked link',ids(pg)==['m5'],ids(pg))
    # list
    pg.goto(BASE+'members.html'); pg.wait_for_timeout(80)
    seg=pg.eval_on_selector_all('#segs button','e=>e.map(x=>x.textContent.replace(/\\s+/g," ").trim())'); print(seg)
    exp=['전체 9','정상 4','이메일 인증 대기 1','휴대전화 인증 대기 1','잠김 1','이용 정지 1','탈퇴 1']
    ok('seg counts',seg==exp,seg)
    ok('9 rows',len(ids(pg))==9)
    hdr=pg.inner_text('.mtable thead'); ok('columns',all(k in hdr for k in ['이름 · 회사','이메일','휴대전화','상태','가입일','요청 수','마지막 로그인']),hdr)
    t=pg.inner_text('.mtable'); ok('phone masked',('010-****-5678' in t) and '010-2345-5678' not in t)
    ok('m1 5 requests',re.search(r'5건',pg.inner_text('tr[data-id=m1]')) is not None,pg.inner_text('tr[data-id=m1]'))
    pg.fill('#fq','hanbit'); ok('search email',ids(pg)==['m1'],ids(pg))
    pg.fill('#fq','010-6789'); ok('search phone (unmasked digits)',ids(pg)==['m5'],ids(pg))
    pg.fill('#fq','45-5678'); ok('search phone mid+tail',ids(pg)==['m1'],ids(pg))
    pg.fill('#fq','소담'); ok('search company',ids(pg)==['m6'],ids(pg))
    pg.fill('#fq','zzz'); ok('search empty','없습니다' in pg.inner_text('.mtable'))
    pg.fill('#fq','예시테스트'); pg.fill('#fq','')
    pg.click('#segs [data-s=active]'); ok('seg active 4',len(ids(pg))==4,ids(pg))
    pg.fill('#fq','한'); ok('seg+search',sorted(ids(pg))==['m1','m4'],ids(pg))
    pg.fill('#fq',''); pg.click('#segs [data-s=pending_email]'); ok('pending_email m7',ids(pg)==['m7'])
    pg.click('#segs [data-s=withdrawn]'); ok('withdrawn m9 (no personal data)',ids(pg)==['m9'] and '탈퇴 회원' in pg.inner_text('.mtable') and '파기됨' in pg.inner_text('.mtable'))
    pg.click('#segs [data-s=all]'); pg.click('tr[data-id=m1] a.hn'); pg.wait_for_url('**/member.html?id=m1'); ok('row link -> detail',True)
    # m1 detail
    ok('m1 title','김지은' in pg.inner_text('h1') and '한빛투어' in pg.inner_text('h1'))
    ok('m1 actions',acts(pg)==['revoke','suspend','transfer','withdraw'],acts(pg))
    ok('m1 profile masked','010-****-5678' in pg.inner_text('#profile') and 'jieun.kim@hanbit-tour.example' in pg.inner_text('#profile'))
    ok('m1 5 rfp rows',pg.locator('#rfpTable tbody tr').count()==5)
    hrefs=pg.eval_on_selector_all('#rfpTable a','e=>e.map(x=>x.getAttribute("href"))'); ok('rfp rows link to rfp.html',hrefs==['rfp.html?id=MG-2610-020','rfp.html?id=MG-2610-017','rfp.html?id=MG-2610-014'] or sorted(hrefs)==sorted(['rfp.html?id=MG-2610-020','rfp.html?id=MG-2610-017','rfp.html?id=MG-2610-014']),hrefs)
    ok('share link active 014','사용 중' in pg.inner_text('#shareTable') and 'MG-2610-014' in pg.inner_text('#shareTable'))
    ok('access log 3 months', pg.locator('#accessTable tbody tr').count()==7)
    ok('audit has signup','가입 완료' in pg.inner_text('#auditTable') and 'ACC_WELCOME' in pg.inner_text('#auditTable'))
    ok('link request box','MG-2609-011' in pg.inner_text('#h-lr ~ .lr-box') and '휴대전화 번호 일치' in pg.inner_text('#h-lr ~ .lr-box'))
    ok('withdraw guard hint shown','진행 중인 요청이 1건' in pg.inner_text('#dside'))
    pg.click('[data-act=withdraw]'); pg.wait_for_timeout(80)
    ok('withdraw blocked (collecting 014)','진행 중인 요청이 1건' in toast(pg) and 'MG-2610-014' in toast(pg) and pg.locator('.dlg').count()==0,toast(pg))
    ok('still active','정상' in pg.inner_text('.dh .chip'))
    pg.screenshot(path=os.path.join(SHOTS,'member_m1_1280.png'),full_page=True)
    # approve link request needs reason
    pg.click('[data-lr=approve]'); pg.click('.dlg [data-x=ok]'); ok('approve needs reason','사유를 선택' in pg.inner_text('.dlg-err'))
    pg.select_option('#dlgReason','기타'); pg.click('.dlg [data-x=ok]'); ok('기타 needs note','메모' in pg.inner_text('.dlg-err'))
    dlg_ok(pg,'휴대전화 번호 일치 확인')
    ok('linked 6 rows',pg.locator('#rfpTable tbody tr').count()==6)
    ok('approve toast ACC_LINKED','ACC_LINKED' in toast(pg))
    ok('notif log ACC_LINKED','ACC_LINKED' in pg.inner_text('#notifTable'))
    ok('audit link approve reason','연결 승인 MG-2609-011' in pg.inner_text('#auditTable') and '휴대전화 번호 일치 확인' in pg.inner_text('#auditTable'))
    ok('nav badge cleared',pg.locator('.side a[href="members.html"] .nav-badge').count()==0)
    ok('link box shows 승인됨','승인됨' in pg.inner_text('#h-lr ~ .lr-box'))
    # suspend with reason
    pg.click('[data-act=suspend]'); pg.click('.dlg [data-x=ok]'); ok('suspend needs reason','사유를 선택' in pg.inner_text('.dlg-err'))
    dlg_ok(pg,'계정 공유 의심')
    ok('m1 suspended','이용 정지' in pg.inner_text('.dh .chip') and acts(pg)==['revoke','transfer','unsuspend'],acts(pg))
    ok('sessions cleared','없음' in pg.inner_text('#sessN'))
    ok('suspend audit','이용 정지' in pg.inner_text('#auditTable') and '계정 공유 의심' in pg.inner_text('#auditTable'))
    pg.click('[data-act=unsuspend]'); dlg_ok(pg,'사유 해소'); ok('m1 active again','정상' in pg.inner_text('.dh .chip'))
    ctx.close()
    # reject link request (fresh)
    ctx,pg=newpage(); login(pg); pg.goto(BASE+'member.html?id=m1')
    pg.click('[data-lr=reject]'); dlg_ok(pg,'확인 불가'); ok('rejected',('거절됨' in pg.inner_text('#h-lr ~ .lr-box')) and pg.locator('#rfpTable tbody tr').count()==5)
    pg.goto(BASE+'members.html'); ok('badge gone after reject',pg.locator('.side a[href="members.html"] .nav-badge').count()==0)
    # revoke sessions
    pg.goto(BASE+'member.html?id=m1'); pg.click('[data-act=revoke]'); dlg_ok(pg,'기기 분실 신고'); ok('revoke ok','종료' in toast(pg) and '없음' in pg.inner_text('#sessN'))
    ok('revoke no more (guard)','revoke' in acts(pg)); pg.click('[data-act=revoke]'); ok('revoke guard toast','종료할 세션이 없습니다' in toast(pg))
    # m5 unlock
    pg.goto(BASE+'member.html?id=m5'); ok('m5 locked actions',acts(pg)==['transfer','unlock'],acts(pg))
    ok('m5 locked info','잠금' in pg.inner_text('#profile') and '10회' in pg.inner_text('#profile'))
    pg.click('[data-act=unlock]'); dlg_ok(pg,'본인 확인 완료(전화)'); ok('m5 unlocked','정상' in pg.inner_text('.dh .chip') and '실패 횟수' in toast(pg))
    pg.goto(BASE+'dashboard.html'); ok('locked count 0',pg.locator('#accSum [data-key=locked].zero').count()==1)
    # m6 suspended
    pg.goto(BASE+'member.html?id=m6'); ok('m6 actions',acts(pg)==['revoke','transfer','unsuspend'],acts(pg))
    # m7 pending_email
    pg.goto(BASE+'member.html?id=m7'); ok('m7 resend only',acts(pg)==['resend'],acts(pg)); ok('m7 purge info','72시간' in pg.inner_text('#profile') and '10/11' in pg.inner_text('.dh'),pg.inner_text('.dh'))
    pg.click('[data-act=resend]'); dlg_ok(pg,'수신 확인 요청(고객 문의)'); ok('resend logged','ACC_EMAIL_CODE' in toast(pg) and pg.locator('#notifTable tbody tr').count()==2 and '2/10' in toast(pg))
    pg.evaluate("()=>{const S=JSON.parse(sessionStorage.getItem('micego_admin_state_v1'));S.members.find(m=>m.id=='m7').sends=10;sessionStorage.setItem('micego_admin_state_v1',JSON.stringify(S))}")
    pg.goto(BASE+'member.html?id=m7'); pg.click('[data-act=resend]'); ok('resend cap 10/day','10회' in toast(pg) and pg.locator('.dlg').count()==0)
    pg.goto(BASE+'member.html?id=m8'); ok('m8 no actions',pg.locator('#tbtns').count()==0 and '휴대전화 인증' in pg.inner_text('#dside'))
    pg.goto(BASE+'member.html?id=m9'); ok('m9 no actions retention',pg.locator('#tbtns').count()==0 and '3' in pg.inner_text('#retained') and '탈퇴 회원' in pg.inner_text('h1'))
    ok('m9 share disabled','탈퇴로 중지' in pg.inner_text('#shareTable'))
    pg.goto(BASE+'member.html?id=NOPE'); ok('unknown member empty','찾을 수 없습니다' in pg.inner_text('main'))
    ctx.close()
    # transfer
    ctx,pg=newpage(); login(pg); pg.goto(BASE+'member.html?id=m3')
    ok('m3 withdraw blocked (delivered)',True); pg.click('[data-act=withdraw]'); ok('withdraw blocked delivered','MG-2610-012' in toast(pg))
    pg.click('[data-act=transfer]'); pg.click('.dlg [data-x=ok]'); ok('transfer needs email','이메일을 입력' in pg.inner_text('.dlg-err'))
    pg.fill('#dlgTo','nobody@x.example'); pg.click('.dlg [data-x=ok]'); ok('transfer unknown','가입한 회원이 없습니다' in pg.inner_text('.dlg-err'))
    pg.fill('#dlgTo','jihun.oh@hanul-promotion.example'); pg.click('.dlg [data-x=ok]'); ok('transfer to locked blocked','정상(active)' in pg.inner_text('.dlg-err') and '잠김' in pg.inner_text('.dlg-err'),pg.inner_text('.dlg-err'))
    pg.fill('#dlgTo','seojin.yoon@purungil.example'); pg.click('.dlg [data-x=ok]'); ok('transfer to self','같은 회원' in pg.inner_text('.dlg-err'))
    pg.fill('#dlgTo','dohyun.han@miraeedu.example'); pg.click('.dlg [data-x=ok]'); ok('transfer needs reason','사유를 선택' in pg.inner_text('.dlg-err'))
    dlg_ok(pg,'담당자 변경(퇴사·인사이동)')
    ok('transferred toast','OPS_RFP_TRANSFER' in toast(pg) and '한도현' in toast(pg),toast(pg))
    ok('m3 rfp gone',pg.locator('#rfpTable tbody tr').count()==0)
    ok('m3 audit+manual notif','요청 이관(보냄)' in pg.inner_text('#auditTable') and '직접 발송 필요' in pg.inner_text('#notifTable'))
    pg.click('[data-act=transfer]') if pg.locator('[data-act=transfer]').count() else None
    ok('m3 transfer guard after (no rfp)','이관할 수 있는 진행 중 요청이 없습니다' in toast(pg))
    pg.goto(BASE+'member.html?id=m4'); ok('m4 got rfp',pg.locator('#rfpTable tbody tr').count()==2 and 'MG-2610-012' in pg.inner_text('#rfpTable') and '요청 이관(받음)' in pg.inner_text('#auditTable'))
    pg.goto(BASE+'rfp.html?id=MG-2610-012'); ok('rfp 012 owner now 한도현','한도현' in pg.inner_text('#ownerBox') and '이관' in pg.inner_text('#histTable'))
    ok('rfp owner link',pg.get_attribute('#ownerLink','href')=='member.html?id=m4')
    ok('012 pick otp pending (delivered)','대기' in pg.inner_text('#ownerBox') and '010-****-7788' in pg.inner_text('#ownerBox'),pg.inner_text('#ownerBox'))
    # transfer revokes share link
    pg.goto(BASE+'member.html?id=m1'); pg.click('[data-act=transfer]')
    pg.select_option('#dlgRfp','MG-2610-014'); pg.fill('#dlgTo','sua.im@sejong-medical.example'); dlg_ok(pg,'담당자 변경(퇴사·인사이동)')
    pg.goto(BASE+'member.html?id=m1'); ok('m1 share revoked after transfer','회원이 끔' in pg.inner_text('#shareTable') or '사용 중' not in pg.inner_text('#shareTable'))
    ctx.close()
    # withdraw m2 (only won) + auto cancel path on m1
    ctx,pg=newpage(); login(pg); pg.goto(BASE+'member.html?id=m2')
    pg.click('[data-act=transfer]'); ok('m2 no transferable','이관할 수 있는' in toast(pg))
    pg.click('[data-act=withdraw]'); pg.select_option('#dlgReason','회원 본인 요청(고객센터)'); pg.click('.dlg [data-x=ok]'); ok('withdraw needs 본인 요청 확인 checkbox','본인 요청 확인' in pg.inner_text('.dlg-err'))
    pg.check('#dlgOwn'); pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(120)
    ok('m2 withdrawn','탈퇴' in pg.inner_text('.dh .chip') and pg.locator('#tbtns').count()==0)
    ok('personal data destroyed','sua.im' not in pg.inner_text('#profile') and '파기됨' in pg.inner_text('#profile'))
    ok('retention note 1건','1건' in pg.inner_text('#retained') and '3년' in pg.inner_text('#retained'))
    ok('ACC_WITHDRAWN logged','ACC_WITHDRAWN' in pg.inner_text('#notifTable') and '본인 요청 확인' in pg.inner_text('#auditTable'))
    ok('share disabled','탈퇴로 중지' in pg.inner_text('#shareTable'))
    st=state(pg); ok('m2 email empty in store',[m['email'] for m in st['members'] if m['id']=='m2']==[''])
    pg.goto(BASE+'members.html'); ok('list counts after',pg.inner_text('#segs button[data-s=withdrawn]').replace('\n',' ').endswith('2'))
    # m1 withdraw with auto-cancel: make 014 cancelled first
    pg.evaluate("()=>{const S=JSON.parse(sessionStorage.getItem('micego_admin_state_v1'));S.rfps.find(r=>r.id=='MG-2610-014').state='cancelled';sessionStorage.setItem('micego_admin_state_v1',JSON.stringify(S))}")
    pg.goto(BASE+'member.html?id=m1'); pg.click('[data-act=withdraw]'); ok('dialog lists auto-cancel','MG-2610-017' in pg.inner_text('.dlg') and 'MG-2610-020' in pg.inner_text('.dlg') and '자동으로 취소' in pg.inner_text('.dlg'))
    pg.select_option('#dlgReason','회원 본인 요청(고객센터)'); pg.check('#dlgOwn'); pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(120)
    ok('m1 withdrawn + auto-cancelled toast','탈퇴 처리했습니다' in toast(pg) and '2건 자동 취소' in toast(pg),toast(pg))
    st=state(pg); ok('017/020 cancelled',[r['state'] for r in st['rfps'] if r['id'] in ('MG-2610-017','MG-2610-020')]==['cancelled','cancelled'] or sorted(r['state'] for r in st['rfps'] if r['id'] in ('MG-2610-017','MG-2610-020'))==['cancelled','cancelled'])
    pg.goto(BASE+'rfp.html?id=MG-2610-017'); ok('rfp history has auto-cancel','회원 탈퇴로 자동 취소' in pg.inner_text('#histTable'))
    # rfp owner box on 014 / 009 / 021 (fresh)
    pg.click('#resetLink'); pg.wait_for_load_state(); pg.wait_for_timeout(200)
    pg.goto(BASE+'rfp.html?id=MG-2610-014'); ob=pg.inner_text('#ownerBox'); ok('014 owner 회원 · 김지은 + share',('회원 · 김지은' in ob) and '사용 중' in ob and pg.get_attribute('#ownerLink','href')=='member.html?id=m1',ob)
    pg.goto(BASE+'rfp.html?id=MG-2610-009'); ob=pg.inner_text('#ownerBox'); ok('009 won otp line','완료 2026-09-25 10:31 (010-****-8642)' in ob,ob)
    pg.goto(BASE+'rfp.html?id=MG-2610-021'); ob=pg.inner_text('#ownerBox'); ok('021 비회원','비회원' in ob and pg.locator('#ownerLink').count()==0,ob)
    # operator won without OTP record
    pg.goto(BASE+'rfp.html?id=MG-2610-012'); pg.locator('[data-sel=selected]').nth(1).click(); pg.click('[data-to=won]'); pg.check('.dlg input[name=dlgConsentMethod][value=email_reply]'); pg.fill('#dlgConsentNote','메일 회신으로 선정과 연락처 전달 동의 확인'); pg.click('.dlg [data-x=ok]'); pg.wait_for_timeout(120)
    ok('012 won: proxy consent recorded (no OTP)','대리 확정' in pg.inner_text('#ownerBox') and '이메일 회신' in pg.inner_text('#ownerBox'),pg.inner_text('#ownerBox'))
    # settings
    pg.goto(BASE+'settings.html#rules'); pg.evaluate('location.reload()'); pg.wait_for_timeout(300)
    mr=pg.inner_text('#memberRules'); ok('member rules table',all(k in mr for k in ['10자 이상','유효 10분','유효 3분','15분','30분','72시간','10분 잠금','3개월','ORG_PICK_OTP']),mr[:200])
    pg.goto(BASE+'settings.html#prereq'); pg.evaluate('location.reload()'); pg.wait_for_timeout(300)
    pr=pg.inner_text('#prereqTable'); ok('prereq new items','SMS 대행사' in pr and '유출' in pr and '약관 전문' in pr and '개정 공지' in pr and pg.locator('#prereqTable tbody tr').count()==12)
    pg.goto(BASE+'settings.html#notify'); pg.evaluate('location.reload()'); pg.wait_for_timeout(300)
    nt=pg.inner_text('#notify')
    ok('notify new IDs',all(k in nt for k in ['ACC_EMAIL_CODE','ACC_EMAIL_EXISTS','ACC_SMS_OTP','ORG_PICK_OTP','ACC_WELCOME','ACC_LINKED','ACC_PW_RESET','ACC_PW_CHANGED','ACC_EMAIL_CHANGED','ACC_PHONE_CHANGED','ACC_LOCKED','ACC_WITHDRAWN','OPS_ACC_LINK','OPS_RFP_TRANSFER']))
    pg.goto(BASE+'settings.html#system'); pg.evaluate('location.reload()'); pg.wait_for_timeout(300); ok('doc v2.0','v2.0' in pg.inner_text('#system'))
    ctx.close()
    # old-session compatibility: state without members gets filled
    ctx,pg=newpage(); login(pg); pg.goto(BASE+'dashboard.html')
    pg.evaluate("()=>{const S=JSON.parse(JSON.stringify(MOCK_DATA));for(const k of ['members','shareLinks','linkRequests','memberAudit','memberLog'])delete S[k];S.rfps.forEach(r=>{delete r.ownerId;});sessionStorage.setItem('micego_admin_state_v1',JSON.stringify(S))}")
    pg.goto(BASE+'members.html'); ok('old session filled',len(ids(pg))==9)
    pg.goto(BASE+'rfp.html?id=MG-2610-014'); ok('old session owner filled','김지은' in pg.inner_text('#ownerBox'))
    ctx.close()
    # responsive
    for w in (360,768,1280):
        ctx,pg=newpage(w,800); login(pg)
        for n in ['members.html','members.html?filter=link','member.html?id=m1','member.html?id=m5','member.html?id=m7','member.html?id=m8','member.html?id=m9','member.html?id=m3','rfp.html?id=MG-2610-014','rfp.html?id=MG-2610-009','rfp.html?id=MG-2610-021','dashboard.html','settings.html#rules','settings.html#notify','settings.html#prereq']:
            pg.goto(BASE+n); pg.evaluate('location.reload()'); pg.wait_for_timeout(350)
            pg.add_style_tag(content='body{overflow-x:visible!important}html{overflow-x:visible!important}')
            sw=pg.evaluate('document.documentElement.scrollWidth'); cw=pg.evaluate('document.documentElement.clientWidth')
            ok(f'no overflow {n} @{w}',sw<=cw,(sw,cw))
        for n in ['../docs/state-transitions.html','../docs/notification-library.html','../docs/state-transitions.html#member','../docs/notification-library.html#t-ACC_SMS_OTP']:
            pg.goto(BASE+n); pg.wait_for_timeout(500)
            sw=pg.evaluate('document.documentElement.scrollWidth'); cw=pg.evaluate('document.documentElement.clientWidth')
            ok(f'no overflow docs {n} @{w}',sw<=cw,(sw,cw))
        pg.goto(BASE+'../docs/state-transitions.html'); ok('doc v2.0 + ACC-T1..T9 + share', 'v2.0' in pg.inner_text('h1') and all(f'ACC-T{i}' in pg.inner_text('#member') for i in range(1,10)) and '공유 링크' in pg.inner_text('#share') and 'ORG_PICK_OTP' in pg.inner_text('#transitions'))
        for n,nm in [('members.html','members'),('member.html?id=m1','member_m1')]:
            if w in (360,1280):
                pg.goto(BASE+n); pg.wait_for_timeout(300); pg.screenshot(path=os.path.join(SHOTS,f'{nm}_{w}.png'),full_page=True)
        ctx.close()
    b.close()
print('ERRS',errs); print('FAILS',[r[0] for r in res if not r[1]])
